name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: |
        clang --version
        bison --version
        flex --version

    - name: Make debug
      run: make VERSION=debug
  
    - name: Make release
      run: make VERSION=release

    - name: Test debug
      run: make test VERSION=debug

    - name: Test release
      run: make test VERSION=release
