name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Apt install things
      run: apt install clang-10

    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 10

    - name: Install dependencies
      run: make

    - name: Run check
      run: make test

    - name: Run distcheck
      run: make test VERSION=release
