name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.8.0
      with:
        version: 10
        force-version: 1
        ubuntu-version: 20.04
        cached: 1
        env: 1

    - name: Install dependencies
      run: make

    - name: Run check
      run: make test

    - name: Run distcheck
      run: make test VERSION=release
